### PR TITLE
nix: Use nceplibs and esmf from VulcanClimateModeling/packages

### PR DESCRIPTION
**Pull request by nbren12**
Johann and I have created at repository of package definitions at
VulcanClimateModeling/packages. This refactors the fv3gfs-fortran nix environment to use those external dependencies.

### CODE REVIEW

**Comment by nbren12** [comment]
I think this build will fail because we won't have ssh keys for the packages github repo. Maybe it will work though.

**Comment by nbren12** [comment]
See https://github.com/VulcanClimateModeling/secret-plumbing-terraform/issues/4

**Comment by nbren12** [comment]
We should publicly release the packages repo before merging this PR.

**Comment by nbren12** [comment]
nix-mac is actually still broken with this build. still worth merging.

**Comment by nbren12** [comment]
I just opened up ai2cm/packages so we can merge this now.

**Review by jdahm — APPROVED** [review]
Works on my laptop!

**Pull request merged**
