### PR TITLE
Split update_atmos_radiation_physics into two subroutines

### PR DESCRIPTION
**Pull request by spencerkclark**
This PR splits `update_atmos_radiation_physics` into two subroutines in a backwards compatible way.  This would enable splitting the calls to the radiation and the physics into two functions in the Python wrapper.

Just posting as a draft for now if we decide to go this route.

### CODE REVIEW

**Comment by ofuhrer** [comment]
@elynnwu

**Comment by spencerkclark** [comment]
#317 by @nbren12 encompasses what was implemented in this PR, so it can be closed.

**Comment by nbren12** [comment]
Ha great minds think alike...lesson to the future to just merge stuff unless we have a good reason not to.

**Comment by spencerkclark** [comment]
All good.  Splitting off the pre-radiation code was a good idea too, which was not implemented in this PR.

**Pull request closed without merging**
